#!/bin/bash
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/bg-indigo-600/bg-accent-1/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/hover:bg-indigo-500/hover:bg-accent-1-hover/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/active:bg-indigo-700/active:bg-accent-1-active/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/focus:ring-indigo-200/focus:ring-accent-1-light/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/focus:border-indigo-700/focus:border-accent-1-border-active/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/border-indigo-200/border-accent-1-light/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/bg-indigo-100/bg-accent-1-light\/30/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/text-indigo-800/text-accent-1-active/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/focus:ring-indigo-400/focus:ring-accent-1-hover/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/text-indigo-600/text-accent-1/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/hover:text-indigo-900/hover:text-accent-1-active/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/border-indigo-400/border-accent-1-border/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/hover:border-indigo-300/hover:border-accent-1-hover/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/border-indigo-500/border-accent-1/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/focus:border-indigo-500/focus:border-accent-1/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/focus:ring-indigo-500/focus:ring-accent-1/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/text-indigo-400/text-accent-1-hover/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/text-indigo-700/text-accent-1-active/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/dark:text-indigo-300/dark:text-accent-1-light/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/dark:text-indigo-400/dark:text-accent-1-hover/g'

find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/bg-gray-600/bg-accent-2/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/hover:bg-gray-500/hover:bg-accent-2-hover/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/active:bg-gray-900/active:bg-accent-2-active/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/focus:ring-gray-500/focus:ring-accent-2/g'

find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/bg-green-600/bg-success/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/hover:bg-green-700/hover:bg-success-hover/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/text-green-800/text-success-active/g'
find src/Views public/js -type f -name "*.php" -o -name "*.js" | xargs sed -i 's/bg-green-100/bg-success-light/g'

