<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Released Documents Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        html, body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            padding-top: .5in;
            padding-left: .5in;
            padding-right: .5in;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header img {
            width: 60px;
            height: auto;
        }
        .header p {
            margin: 0;
            font-size: 14px;
        }
        .header .division {
            font-weight: bold;
            margin-top: 5px;
            font-size: 22px;
        }
        .title {
            text-align: center;
            font-weight: bold;
            font-size: 20px;
            margin-bottom: 10px;
        }
        .report-details {
            font-size: 12px;
        }
        .charts-container {
            margin-top: 15px;
            margin-bottom: 15px;
            text-align: center;
        }
        .charts-container img {
            max-width: 45%;
            height: auto;
            margin: 25px;
        }
        .filters {
            margin-top: 15px;
            margin-bottom: 10px;
            font-size: 11px;
            font-style: italic;
        }
        .styled-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
            margin-bottom: .3in;
        }
        .styled-table th, .styled-table td {
            border: 1px solid #ddd;
            padding: 6px;
        }
        .styled-table th {
            background-color: #f2f2f2;
            text-align: left;
        }
        .footer {
            text-align: right;
            font-size: 10px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <img src="https://upload.wikimedia.org/wikipedia/commons/2/23/Seal_of_the_Department_of_Education_of_the_Philippines.png" alt="DepEd Logo">
        <p>Republic of the Philippines</p>
        <p>Department of Education</p>
        <p>Region X - Northern Mindanao</p>
        <p class="division">SCHOOLS DIVISION OF ILIGAN CITY</p>
    </div>

    <h2 class="title">Released Documents Report</h2>

    <div class="report-details">
        <strong>Department:</strong> {{ $departmentName }}<br>
        <strong>Date Generated:</strong> {{ now()->format('F d, Y h:i A') }}
    </div>

    @if (!empty($charts))
        <div class="charts-container">
            <h3 class="title">Charts</h3>
            @foreach ($charts as $chart)
                @if ($chart)
                    <img src="{{ $chart }}">
                @endif
            @endforeach
        </div>
    @endif

    <div class="filters">
        <strong>Filters Applied:</strong>
        @if(empty(array_filter($filters)))
            None
        @else
            @foreach($filters as $key => $value)
                @if($value && $value !== 'all')
                    <span>{{ ucfirst(str_replace('_', ' ', $key)) }}: <strong>
                        @if ($key === 'month')
                            {{ date('F', mktime(0, 0, 0, $value, 10)) }}
                        @else
                            {{ $value }}
                        @endif
                    </strong>;</span>
                @endif
            @endforeach
        @endif
    </div>

    <table class="styled-table">
        <thead>
            <tr>
                <th>Tracking Code</th>
                <th>Title</th>
                <th>Purpose</th>
                <th>Submitted By</th>
                <th>Released At</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($releasedDocuments as $doc)
                <tr>
                    <td>{{ $doc->tracking_code }}</td>
                    <td>{{ $doc->title }}</td>
                    <td>{{ $doc->purpose->name }}</td>
                    <td>{{ $doc->guest_info['name'] ?? 'N/A' }}</td>
                    <td>{{ $doc->updated_at->format('Y-m-d h:i A') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center;">No released documents found for the selected criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by the Document Tracking System.
    </div>

</body>
</html>
